// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjF1aXoqdTUUTHEcYW_lEXE10M1UPA9G8',
    appId: '1:577213484188:web:3eb3d370c9d8609000b159',
    messagingSenderId: '577213484188',
    projectId: 'cdns-fb325',
    authDomain: 'cdns-fb325.firebaseapp.com',
    storageBucket: 'cdns-fb325.appspot.com',
    measurementId: 'G-VK34QVYZX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCskezdtN0CXPmyQj8x7uPHJ2MH6rtMW6Q',
    appId: '1:577213484188:android:75d6e258b6f4a85700b159',
    messagingSenderId: '577213484188',
    projectId: 'cdns-fb325',
    storageBucket: 'cdns-fb325.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqhTeM2t5ZR5HJRDLJaA3WX9T3csT-vdA',
    appId: '1:577213484188:ios:9eb9fc72b35a7d0f00b159',
    messagingSenderId: '577213484188',
    projectId: 'cdns-fb325',
    storageBucket: 'cdns-fb325.appspot.com',
    androidClientId: '577213484188-4gskiqut4h9ebeeakhn9v2r3ig71till.apps.googleusercontent.com',
    iosClientId: '577213484188-v7ocnn60rjncd11i09stm6ka0tbes6r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqhTeM2t5ZR5HJRDLJaA3WX9T3csT-vdA',
    appId: '1:577213484188:ios:9eb9fc72b35a7d0f00b159',
    messagingSenderId: '577213484188',
    projectId: 'cdns-fb325',
    storageBucket: 'cdns-fb325.appspot.com',
    androidClientId: '577213484188-4gskiqut4h9ebeeakhn9v2r3ig71till.apps.googleusercontent.com',
    iosClientId: '577213484188-v7ocnn60rjncd11i09stm6ka0tbes6r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientFlutter',
  );
}
